USE nominal_dev;

-- HOSTELERIA
INSERT INTO nominal_dev.agreement (name) VALUES ("Hosteleria");

-- EMPLOYEE CATEGORIES
INSERT INTO nominal_dev.agreement_emp_category (agreement,name,level) VALUES
    ("Jefe/a de recepción",	1)
    ("Primer/a conserje",	1)
    ("Jefe/a de cocina",	1)
    ("Jefe/a de comedor", 	1)
    ("Contable general",	1)
    ("Primer/a encargado/a de mostrador",	1)
    ("Primer/a jefe/a de sala", 	1)
    ("Encargado/a general pisos y limpieza (antes gobernanta/e",)	1)
    ("Monta discos",	1)
    ("Jefe/a de operaciones de catering",	1)
    ("Jefe/a de personal de catering",	1)
    ("Jefe/a de compras de catering",	1)
    ("Jefe/a de administración de catering",	1)
    ("Jefe/a de mantenimiento de catering",	1)
    ("Jefe/a de supervisores de catering",	1)
    ("Encargado/a de mantenimiento y servicios (antes encargado/a de trabajos",)	1)
    ("Jefe/a de bar",	2)
    ("Segundo/a jefe/a de cocina",	2)
    ("Segundo/a jefe/a de comedor",	2)
    ("Jefe/a repostería",	2)
    ("Segundo/a jefe/a de sala",	2)
    ("Segundo/a encargado/a de mostrador",	2)
    ("Mayordomo/a de pisos",	2)
    ("Segundo/a Jefe/a de Recepción",	2)
    ("Interventor/a",	2)
    ("Supervisor/a de catering",	2)
    ("Jefe/a de Sala de catering",	2)
    ("Jefe/a de repostería de catering",	2)
    ("Encargado/a de sección pisos y limpieza (antes Subgobernanta/e",)	2)
    ("Segundo/a jefe/a de cocina de catering",	2)
    ("Jefe/a administrativo/a",	2)
    ("Segundo/a encargado/a de mantenimiento y servicios (en aquellos centros donde existe este puesto de trabajo",)	2)
    ("Jefe/a de partida",	3)
    ("Jefe/a de sector", 	3)
    ("Segundo/a jefe/a de bar", 	3)
    ("Dependiente/a de primera", 	3)
    ("Segundo/a conserje", 	3)
    ("Recepcionista",	3)
    ("Oficial/a administrativo/a de 1ª",	3)
    ("Manocorrentista", 	3)
    ("Encargado/a de lencería de catering",	3)
    ("Especialista en dietética y nutrición en catering (BUP o equivalente más 2 años de especialización",)	3)
    ("Cajero/a",	3)
    ("Contable",	3)
    ("Encargado/a de economato",	3)
    ("Conserje/a de noche",	3)
    ("Encargado/a de economato catering",	3)
    ("Encargado/a sala limpieza catering",	3)
    ("Jefe/a de equipo de catering",	3)
    ("Oficial/a 1ª administrativo/a de catering",	3)
    ("Relaciones públicas (titulado/a y con idiomas",)	3)
    ("Encargado/a de lencería y lavandería", 	4)
    ("Cocinero/a", 	4)
    ("Planchista", 	4)
    ("Cafetero/a", 	4)
    ("Oficial/a repostero/a", 	4)
    ("Dependiente/a 2ª",	4)
    ("Camarero/a de sala", 	4)
    ("Cocinero/a de catering",	4)
    ("Preparador/a de catering", 	4)
    ("Fontanero/a", 	4)
    ("Mecánico/a-calefactor/a",	4)
    ("Conductor/a", 	4)
    ("Jardinero/a", 	4)
    ("Albañil", 	4)
    ("Carpintero/a", 	4)
    ("Electricista",	4)
    ("Pintor/a",	4)
    ("Tapicero/a",	4)
    ("Panadero/a",	4)
    ("Animador/a y monitor/a",	4)
    ("Camarero/a bar",	4)
    ("Camarero/a comedor",	4)
    ("Camarero/a sala de fiestas",	4)
    ("Oficial/a administrativo/a 2ª",	4)
    ("Oficial/a de repostería de catering",	4)
    ("Oficial/a de mantenimiento de catering",	4)
    ("Conductor/a de catering",	4)
    ("Mecánico/a de catering",	4)
    ("Oficial/a administrativo/a 2ª catering",	4)
    ("Camarero/a de pisos",	4)
    ("Ayudante/a de planchista",	5)
    ("Ayudante/a de cocina", 	5)
    ("Ayudante/a de repostería",	5)
    ("Telefonista",	5)
    ("Facturista",	5)
    ("Taquillero/a", 	5)
    ("Ayudante/a recepción o conserjería", 	5)
    ("Ayudante/a de sala o mostrador", 	5)
    ("Ayudante/a de comedor o bar", 	5)
    ("Auxiliar administrativo/a caja o contabilidad",	5)
    ("Ayudante/a de preparación catering",	5)
    ("Ayudante/a de economato",	5)
    ("Ayudante/a de economato catering",	5)
    ("Ayudante/a de cocina catering",	5)
    ("Ayudante/a de repostería catering",	5)
    ("Ayudante/a de jefe/a de equipo catering",	5)
    ("Auxiliar administrativo/a catering",	5)
    ("Lavandero/a de catering",	5)
    ("Bodeguero/a",	5)
    ("Portero/a de coches", 	6)
    ("Portero/a recibidor/a de sala de fiestas", 	6)
    ("Guardarropa", 	6)
    ("Peón", 	6)
    ("Pinche", 	6)
    ("Fregador/a", 	6)
    ("Vigilante/a de noche",	6)
    ("Portero/a de servicio",	6)
    ("Mozo/a de equipajes",	6)
    ("Niñero/a",	6)
    ("Piscinero/a",	6)
    ("Mozo/a de habitaciones",.	6)
    ("Marmitón/a", 	6)
    ("Ayudante/a de cafetín", 	6)
    ("Calefactor/a",	6)
    ("Ayudante/a de mecánico/a", 	6)
    ("Ayudante/a de tapicero/a", 	6)
    ("Ayudante/a de jardinero/a", 	6)
    ("Ayudante/a de albañil Ascensorista",	6)
    ("Ayudante/a de fontanero/a", 	6)
    ("Ayudante/a de carpintero/a",	6)
    ("Ayudante/a de electricista", 	6)
    ("Ayudante/a de pintor/a", 	6)
    ("Mozo/a de almacén",	6)
    ("Lencero/a",	6)
    ("Lavandero/a",	6)
    ("Costurero/a",	6)
    ("Planchador/a",	6)
    ("Limpiador/a",	6)
    ("Botones",	6)
    ("Ascensorista",	6)
    ("Guarda exterior de catering",	6)
    ("Limpiador/a o fregador/a de catering",	6)
    ("Pinche de catering",	6)
    ("Peón de catering",	6)
    ("Socorrista",	6);